AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS service account for demo guides'
Parameters:
  PolicyName:
    Type: String
    Description: 'Managed Policy Name'
    Default: 'F5XCServiceAccountPolicyForAWSSite'
Resources:
  SAUser:
    Type: AWS::IAM::User
  SAUserPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref 'PolicyName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: 'ManageUsers'
          Effect: Allow
          Action:
          - 'iam:GetPolicy'
          - 'iam:GetPolicyVersion'
          - 'iam:ListPolicyVersions'
          - 'iam:ListAttachedUserPolicies'
          - 'iam:ListGroupsForUser'
          - 'iam:DeletePolicy'
          - 'iam:GetRole'
          - 'iam:DeleteAccessKey'
          - 'iam:UpdateUser'
          - 'iam:TagRole'
          - 'iam:CreatePolicy'
          - 'iam:ListAccessKeys'
          - 'iam:AttachUserPolicy'
          - 'iam:DeleteUserPolicy'
          - 'iam:UpdateAccessKey'
          - 'iam:CreateRole'
          - 'iam:DeleteRole'
          - 'iam:DeleteUser'
          - 'iam:CreateUser'
          - 'iam:TagUser'
          - 'iam:CreateAccessKey'
          - 'iam:GetUserPolicy'
          - 'iam:PutUserPolicy'
          - 'iam:UpdateRole'
          - 'iam:GetUser'
          - 'iam:DetachUserPolicy'
          Resource: '*'
        - Sid: 'ManageVPCs'
          Effect: Allow
          Action:
          - 'ec2:CreateTags'
          - 'ec2:CreateVpc'
          - 'ec2:CreateSubnet'
          - 'ec2:DescribeAvailabilityZones'
          - 'ec2:CreateRouteTable'
          - 'ec2:CreateRoute'
          - 'ec2:CreateInternetGateway'
          - 'ec2:AttachInternetGateway'
          - 'ec2:AssociateRouteTable'
          - 'ec2:ModifyVpcAttribute'
          - 'ec2:DeleteRouteTable'
          - 'ec2:CreateRoute'
          - 'ec2:ReplaceRoute'
          - 'ec2:DeleteRoute'
          - 'ec2:DeleteInternetGateway'
          - 'ec2:DeleteSubnet'
          - 'ec2:DeleteVpc'
          - 'ec2:Describe*'
          Resource: '*'
      Users: [!Ref 'SAUser']
  SAKeys:
   Type: AWS::IAM::AccessKey
   Properties:
     UserName: !Ref 'SAUser'
Outputs:
  UserName:
    Value: !Ref 'SAUser'
    Description: AWS User name of new user
  AccessKey:
    Value: !Ref 'SAKeys'
    Description: AWS Access Key of new user
  SecretKey:
    Value: !GetAtt [SAKeys, SecretAccessKey]
    Description: AWS Secret Access Key of new user