postgresql-ha:
  commonAnnotations:
    ves.io/virtual-sites: "ha-services-ce/aws-ha-vs"

  clusterDomain: aws-ha.tme-lab-works-oeaclgke.tenant.local  
  kubeVersion: "v1.25.2"

  persistence:
    enabled: true
    size: 30Gi

  postgresql:        
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
      limits:
        memory: 512Mi
        cpu: 1500m

    containerSecurityContext:
      runAsNonRoot: true

    replicaCount: 2
    username: haservices
    password: haservicespass    
    database: haservicesdb
    repmgrUsername: haservices
    repmgrPassword: haservicespass    
    repmgrDatabase: repmgrhaservicesdb

  pgpool:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
      limits:
        memory: 512Mi
        cpu: 1500m
        
    childLifeTime: 3600
    containerSecurityContext:
      runAsNonRoot: true
    
    adminUsername: haservices
    adminPassword: haservicespass