{{- if .Values.nginx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.nginx.name }}
  {{- with .Values.nginx.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
