apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    # HTTP 1.1 support
    proxy_http_version 1.1;

    resolver 127.0.0.11 valid=5s ipv6=off;

    proxy_cache_path /data/nginx/cache levels=1:2 keys_zone=srv:10m max_size=100m inactive=60m use_temp_path=off;
    proxy_cache_key "$scheme$host$request_uri";
    
    upstream database {
        postgres_server  re2ce.internal dbname=haservicesdb        
                         user=haservices password=haservicespass;
    }

    server {
        listen 8080;

        location /probe {
          add_header Content-Type text/html;
          return 200 'Battle cruiser operational!';
        }

        location / {
            rds_json          on;

            proxy_buffering on;
            proxy_cache srv;
            proxy_ignore_headers Cache-Control;
            proxy_cache_methods GET HEAD POST;          
            proxy_cache_valid  200 302  30s;
            proxy_cache_valid  404      10s;
            proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504 http_429; 

            add_header X-Cache-Status $upstream_cache_status;

            proxy_pass http://localhost:8080/data;          
        }

        location /data {     
          postgres_pass     database;
          postgres_query    "SELECT * FROM articles";
        }
    }